#!/bin/bash

file="mapkit.$1.d.ts"
index="index.d.ts"

touch $file

cat <<EOT >> $file
// Type definitions for MapKit JS 5.0
// Project: https://developer.apple.com/documentation/mapkitjs
// Definitions by: Waseem Dahman <https://github.com/wsmd>

declare namespace mapkit {
  class $1 {}
}
EOT

echo "/// <reference path=\"./$file\" />" >> $index

echo "Created $file"
