#!/bin/bash

file="mapkit.$1.d.ts"
index="mapkit/index.d.ts"

cat <<EOT >> mapkit/$file
$(head -3 $index)

declare namespace mapkit {
  class $1 {}
}
EOT

echo "/// <reference path=\"$file\" />" >> $index
